---
title: "Quiz2A"
author: "sieun Bae"
date: '2019 5 23 '
output: html_document
---

1-a)
```{r}
callMe <- function(x,y){
  if(x==0 | y ==0){
    return (0)
  } else if (x==1) {
    return (y)
  } else if (y==1) {
    return(x)
  } else{
    return(x + callMe(x, y-1))
  }
}

callMe(1,3)
callMe(4,2)
callMe(0,3)
callMe(-6,5)
```

1-b) multiply x and y

1-c) 
```{r}
callMe <- function(x,y){
  if(x==0 | y ==0){
    return (0)
  } else if (x==1) {
    return (y)
  } else if (y==1) {
    return(x)
  } else{
    if (x<0){
      if (y>0){
        return(x + callMe(x, y-1))
      } else{
        return(-x + callMe(x, y+1))
      }
    } else {
      if (y>0){
        return(x + callMe(x,y-1))
      } else{
        return(y + callMe(x-1, y))
      }
    }
  }
}

callMe(2,-5)
callMe(-3,-7)
```

2-a)
```{r}
txhousing %>% filter(city=='Austin' & year == 2007)
```

2-b)
```{r}
txhousing %>% filter(city=='Austin' & year == 2007) %>% arrange(desc(sales))
```
Answer: Austin had the most sales in month 6(June), 2007.

2-c)
```{r}
txhousing %>% select(city, volume, year) %>% group_by(year) %>% filter(min_rank(volume) == 1 | min_rank(desc(volume)) == 1) %>% arrange(year)
```

2-d)
```{r}
txhousing %>% group_by(city) %>% summarise(
  min_sales = min(sales, na.rm = TRUE),
  max_sales = max(sales, na.rm = TRUE),
  diff_sales = max(sales) - min(sales),
  total_listing = sum(listings, na.rm = TRUE)
) %>% arrange(desc(diff_sales))
```

2-e)
```{r}
txhousing %>% select(city, year, month, volume) %>% filter(year == 2011) %>% arrange(city, month) %>% mutate(cityLag = lag(city,1), volumeLag = lag(volume, 1)) %>% filter(city == cityLag) %>% mutate(vol_delta = volumeLag/volume) %>% select(city,year,month,volume,vol_delta) %>% group_by(city) %>% filter(min_rank(desc(vol_delta))==1) %>% arrange(desc(vol_delta))
```

3-a)
```{r}
attach(txhousing)
model <-  lm(sales~listings)

summary(model)
```

3-b)
Answer
B0: 2.266e+01
B1: 1.793e-01

3-c)
It is significant enough.
p-value is lower than 2.2e-16, which is lower than 0.05 so it is significant.

3-d)
Adjusted R-squared value is 0.8491, which is close to 1, so it is a good fit.

3-e)
minimizing some form of summed squared deviations between the data and the fit.




































